-- Migration: Add missing columns to clients table
-- Version: 20250401000002

ALTER TABLE clients ADD COLUMN IF NOT EXISTS response_status VARCHAR(20) DEFAULT 'Pending';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS renewed BOOLEAN DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS rejected BOOLEAN DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS cross_sell_rejected BOOLEAN DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS cross_sell_interested BOOLEAN DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS sequence_cs VARCHAR(20) DEFAULT 'ACTIVE';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS checkin_replied BOOLEAN DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS pre14_sent BOOLEAN DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS pre7_sent BOOLEAN DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS pre3_sent BOOLEAN DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS post1_sent BOOLEAN DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS post4_sent BOOLEAN DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS post8_sent BOOLEAN DEFAULT FALSE;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS post15_sent BOOLEAN DEFAULT FALSE;
