-- Rollback: Remove seeded API keys from system_config
DELETE FROM system_config WHERE key IN (
  'HALOAI_API_URL',
  'WA_API_TOKEN',
  'HALOAI_BUSINESS_ID',
  'HALOAI_CHANNEL_ID',
  'TELEGRAM_BOT_TOKEN',
  'TELEGRAM_AE_LEAD_ID',
  'PROMO_DEADLINE',
  'SURVEY_PLATFORM_URL',
  'CHECKIN_FORM_URL',
  'REFERRAL_BENEFIT',
  'QUOTATION_URL',
  'ACV_HIGH_THRESHOLD',
  'ACV_MID_THRESHOLD',
  'SENIOR_AE_TELEGRAM_IDS',
  'AE_TEAM_TELEGRAM_IDS',
  'ANGRY_KEYWORDS_EXTRA',
  'SILENCE_THRESHOLD_DAYS',
  'JWT_VALIDATE_URL'
);
