DELETE FROM trigger_rules WHERE rule_id IN (
  'HEALTH_LOW_USAGE', 'HEALTH_LOW_NPS', 'HEALTH_LOW_NPS_ESC',
  'CHECKIN_A1_FORM', 'CHECKIN_A1_CALL', 'CHECKIN_A2_FORM', 'CHECKIN_A2_CALL',
  'CHECKIN_B1_FORM', 'CHECKIN_B1_CALL', 'CHECKIN_B2_FORM', 'CHECKIN_B2_CALL',
  'REN60_SKIP_CHECKIN', 'REN60', 'REN45_SKIP_CHECKIN', 'REN45',
  'REN30_BLOCK_NO_QUOTATION', 'REN30', 'REN15', 'REN0', 'REN0_ESC_MID_HIGH',
  'INVOICE_CREATE', 'PAY_PRE14', 'PAY_PRE7', 'PAY_PRE3',
  'PAY_POST1', 'PAY_POST4', 'PAY_POST8', 'PAY_POST15', 'OVERDUE_ESC_D15',
  'NPS1', 'NPS2', 'NPS3', 'REFERRAL',
  'CS_H7', 'CS_H14', 'CS_H21', 'CS_H30', 'CS_H45', 'CS_H60', 'CS_H75', 'CS_H90',
  'CS_LT1', 'CS_LT2', 'CS_LT3'
);
