FROM golang:1.23-alpine

WORKDIR /app

ENV CGO_ENABLED=0
RUN go install github.com/cosmtrek/air@v1.49.0
RUN go install github.com/go-delve/delve/cmd/dlv@v1.21.0

COPY go.mod go.sum ./
RUN go mod download
COPY . ./

EXPOSE 3000 3456

CMD ["air", "-c", ".air.toml"]
