// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Dealls Engineering",
            "url": "https://github.com/Sejutacita"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/dashboard/clients": {
            "get": {
                "description": "Returns all clients for a given workspace. Use \"holding\" to aggregate across member workspaces. Defaults to \"dealls\" if omitted.",
                "tags": [
                    "Dashboard"
                ],
                "summary": "List clients",
                "parameters": [
                    {
                        "type": "string",
                        "default": "dealls",
                        "description": "Workspace slug",
                        "name": "workspace",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.Client"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new client in the specified workspace. Defaults to \"dealls\" workspace if omitted.",
                "tags": [
                    "Dashboard"
                ],
                "summary": "Create client",
                "parameters": [
                    {
                        "type": "string",
                        "default": "dealls",
                        "description": "Workspace slug",
                        "name": "workspace",
                        "in": "query"
                    },
                    {
                        "description": "Client payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dashboard.CreateClientRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.Client"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/dashboard/clients/{company_id}": {
            "get": {
                "description": "Returns a single client by company_id.",
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get client by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/entity.Client"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Partially updates a client by company_id. Accepts a JSON object with fields to update.",
                "tags": [
                    "Dashboard"
                ],
                "summary": "Update client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Soft-deletes a client by company_id (sets blacklisted=true, bot_active=false).",
                "tags": [
                    "Dashboard"
                ],
                "summary": "Delete client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/dashboard/clients/{company_id}/escalations": {
            "get": {
                "description": "Returns all escalation records for a given client.",
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get client escalations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.Escalation"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/dashboard/clients/{company_id}/invoices": {
            "get": {
                "description": "Returns all invoices for a given client.",
                "tags": [
                    "Dashboard"
                ],
                "summary": "Get client invoices",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "company_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.Invoice"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/dashboard/workspaces": {
            "get": {
                "description": "Returns all workspaces. Holding workspace aggregates data from member workspaces.",
                "tags": [
                    "Dashboard"
                ],
                "summary": "List workspaces",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/response.StandardResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/entity.Workspace"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/handoff/new-client": {
            "post": {
                "security": [
                    {
                        "X-Handoff-Secret": []
                    }
                ],
                "description": "Creates a new client record when a Business Development team member hands off a new prospect. Requires HMAC authentication using X-Handoff-Secret header.",
                "tags": [
                    "api"
                ],
                "summary": "Onboard New Client from BD Handoff",
                "parameters": [
                    {
                        "description": "New client handoff payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.HandoffCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Client onboarded successfully",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid HMAC signature",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            }
        },
        "/api/payment/verify": {
            "post": {
                "security": [
                    {
                        "X-Verify-Secret": []
                    }
                ],
                "description": "Verifies and marks a client's payment as paid after AE verification. Sends confirmation to client via WhatsApp and creates tracking record. Requires HMAC authentication using X-Verify-Secret header.",
                "tags": [
                    "api"
                ],
                "summary": "Verify Client Payment",
                "parameters": [
                    {
                        "description": "Payment verification payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_delivery_http_payment.VerifyPaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Payment verified successfully",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid HMAC signature",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "Client not found",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            }
        },
        "/cron/run": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Manually triggers the bot's cron job to process all clients and send scheduled WhatsApp messages. Requires GCP Cloud Scheduler OIDC token authentication.",
                "tags": [
                    "cron"
                ],
                "summary": "Trigger Cron Job",
                "responses": {
                    "200": {
                        "description": "Cron run completed successfully",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized - invalid or missing OIDC token",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error - cron run failed",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            }
        },
        "/readiness": {
            "get": {
                "description": "Health check for service",
                "tags": [
                    "health"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            }
        },
        "/webhook/checkin-form": {
            "post": {
                "description": "Processes check-in form submissions from clients. Marks the client as having replied to check-in and notifies the Account Executive via Telegram.",
                "tags": [
                    "webhook"
                ],
                "summary": "Process Check-in Form Submission",
                "parameters": [
                    {
                        "description": "Check-in form payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CheckinFormRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Checkin form processed successfully",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "404": {
                        "description": "Company not found",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/response.StandardResponse"
                        }
                    }
                }
            }
        },
        "/webhook/wa": {
            "post": {
                "description": "Receives incoming WhatsApp message events from HaloAI. Returns HTTP 200 immediately, then processes the message asynchronously in a background goroutine.",
                "tags": [
                    "webhook"
                ],
                "summary": "Receive WhatsApp Webhook",
                "parameters": [
                    {
                        "description": "WhatsApp webhook payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.WAWebhookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Webhook received (async processing)",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apperror.FieldError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "dashboard.CreateClientRequest": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "string"
                },
                "company_name": {
                    "type": "string"
                },
                "hc_size": {
                    "type": "string"
                },
                "owner_name": {
                    "type": "string"
                },
                "owner_telegram_id": {
                    "type": "string"
                },
                "owner_wa": {
                    "type": "string"
                },
                "pic_email": {
                    "type": "string"
                },
                "pic_name": {
                    "type": "string"
                },
                "pic_role": {
                    "type": "string"
                },
                "pic_wa": {
                    "type": "string"
                },
                "plan_type": {
                    "type": "string"
                },
                "segment": {
                    "type": "string"
                }
            }
        },
        "dto.CheckinFormRequest": {
            "type": "object",
            "required": [
                "company_id"
            ],
            "properties": {
                "company_id": {
                    "type": "string",
                    "example": "KTK-001"
                }
            }
        },
        "dto.CustomerDTO": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "dto.HandoffCreateRequest": {
            "type": "object",
            "required": [
                "company_id",
                "company_name",
                "contract_end",
                "contract_months",
                "contract_start",
                "owner_name",
                "owner_telegram_id",
                "pic_name",
                "pic_wa",
                "segment"
            ],
            "properties": {
                "activation_date": {
                    "type": "string",
                    "example": "2024-01-15"
                },
                "company_id": {
                    "type": "string",
                    "example": "KTK-001"
                },
                "company_name": {
                    "type": "string",
                    "example": "PT Maju Bersama Sejahtera"
                },
                "contract_end": {
                    "type": "string",
                    "example": "2026-01-15"
                },
                "contract_months": {
                    "type": "integer",
                    "example": 12
                },
                "contract_start": {
                    "type": "string",
                    "example": "2024-01-15"
                },
                "owner_name": {
                    "type": "string",
                    "example": "Rina"
                },
                "owner_telegram_id": {
                    "type": "string",
                    "example": "-1001234567890"
                },
                "owner_wa": {
                    "type": "string",
                    "example": "6289876543210"
                },
                "pic_name": {
                    "type": "string",
                    "example": "Budi Santoso"
                },
                "pic_wa": {
                    "type": "string",
                    "example": "6281234567890"
                },
                "segment": {
                    "type": "string",
                    "example": "Mid"
                }
            }
        },
        "dto.MessageDTO": {
            "type": "object",
            "properties": {
                "ack": {
                    "type": "integer"
                },
                "body": {
                    "type": "string"
                },
                "from_me": {
                    "type": "boolean"
                },
                "has_media": {
                    "type": "boolean"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "dto.TriggerDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "messageId": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "dto.UTMDOT": {
            "type": "object",
            "properties": {
                "utm_campaign": {
                    "type": "string"
                },
                "utm_medium": {
                    "type": "string"
                },
                "utm_source": {
                    "type": "string"
                }
            }
        },
        "dto.WAWebhookRequest": {
            "type": "object",
            "properties": {
                "customer": {
                    "$ref": "#/definitions/dto.CustomerDTO"
                },
                "event": {
                    "type": "string"
                },
                "message": {
                    "$ref": "#/definitions/dto.MessageDTO"
                },
                "request_id": {
                    "type": "string"
                },
                "room_id": {
                    "type": "string"
                },
                "trigger": {
                    "$ref": "#/definitions/dto.TriggerDTO"
                },
                "utm": {
                    "$ref": "#/definitions/dto.UTMDOT"
                }
            }
        },
        "entity.Client": {
            "type": "object",
            "properties": {
                "activation_date": {
                    "type": "string"
                },
                "ae_assigned": {
                    "type": "boolean"
                },
                "ae_telegram_id": {
                    "type": "string"
                },
                "backup_owner_telegram_id": {
                    "type": "string"
                },
                "bd_prospect_id": {
                    "type": "string"
                },
                "blacklisted": {
                    "type": "boolean"
                },
                "bot_active": {
                    "type": "boolean"
                },
                "checkin_replied": {
                    "type": "boolean"
                },
                "churn_reason": {
                    "type": "string"
                },
                "company_id": {
                    "type": "string"
                },
                "company_name": {
                    "type": "string"
                },
                "contract_end": {
                    "type": "string"
                },
                "contract_months": {
                    "type": "integer"
                },
                "contract_start": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "cross_sell_interested": {
                    "type": "boolean"
                },
                "cross_sell_rejected": {
                    "type": "boolean"
                },
                "cross_sell_resume_date": {
                    "type": "string"
                },
                "days_since_cs_last_sent": {
                    "type": "integer"
                },
                "feature_update_sent": {
                    "type": "boolean"
                },
                "final_price": {
                    "type": "number"
                },
                "first_time_discount_pct": {
                    "type": "number"
                },
                "hc_size": {
                    "type": "string"
                },
                "last_interaction_date": {
                    "type": "string"
                },
                "last_payment_date": {
                    "type": "string"
                },
                "next_discount_pct_manual": {
                    "type": "number"
                },
                "notes": {
                    "type": "string"
                },
                "nps_score": {
                    "type": "integer"
                },
                "owner_name": {
                    "type": "string"
                },
                "owner_telegram_id": {
                    "type": "string"
                },
                "owner_wa": {
                    "type": "string"
                },
                "payment_status": {
                    "type": "string"
                },
                "payment_terms": {
                    "type": "string"
                },
                "pic_email": {
                    "description": "Fields from existing DB columns previously not mapped",
                    "type": "string"
                },
                "pic_name": {
                    "type": "string"
                },
                "pic_role": {
                    "type": "string"
                },
                "pic_wa": {
                    "type": "string"
                },
                "plan_type": {
                    "type": "string"
                },
                "post15_sent": {
                    "type": "boolean"
                },
                "post1_sent": {
                    "type": "boolean"
                },
                "post4_sent": {
                    "type": "boolean"
                },
                "post8_sent": {
                    "type": "boolean"
                },
                "pre14_sent": {
                    "description": "Invoice reminder flags (from Master Client sheet columns 27-33)",
                    "type": "boolean"
                },
                "pre3_sent": {
                    "type": "boolean"
                },
                "pre7_sent": {
                    "type": "boolean"
                },
                "quotation_link": {
                    "type": "string"
                },
                "quotation_link_expires": {
                    "type": "string"
                },
                "rejected": {
                    "type": "boolean"
                },
                "renewal_date": {
                    "type": "string"
                },
                "renewed": {
                    "type": "boolean"
                },
                "response_status": {
                    "type": "string"
                },
                "risk_flag": {
                    "type": "boolean"
                },
                "segment": {
                    "type": "string"
                },
                "sequence_cs": {
                    "type": "string"
                },
                "usage_score": {
                    "type": "integer"
                },
                "usage_score_avg_30d": {
                    "type": "integer"
                },
                "wa_undeliverable": {
                    "type": "boolean"
                },
                "workspace_id": {
                    "type": "string"
                }
            }
        },
        "entity.Escalation": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "esc_id": {
                    "type": "string"
                },
                "escalation_id": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "notified_party": {
                    "type": "string"
                },
                "priority": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "resolved_at": {
                    "type": "string"
                },
                "resolved_by": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "telegram_message_sent": {
                    "type": "string"
                },
                "workspace_id": {
                    "type": "string"
                }
            }
        },
        "entity.Invoice": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "amount_paid": {
                    "type": "number"
                },
                "collection_stage": {
                    "type": "string"
                },
                "company_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "due_date": {
                    "type": "string"
                },
                "invoice_id": {
                    "type": "string"
                },
                "issue_date": {
                    "type": "string"
                },
                "last_reminder_date": {
                    "type": "string"
                },
                "link_invoice": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "paid_at": {
                    "type": "string"
                },
                "payment_status": {
                    "type": "string"
                },
                "reminder_count": {
                    "type": "integer"
                },
                "workspace_id": {
                    "type": "string"
                }
            }
        },
        "entity.Workspace": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_holding": {
                    "type": "boolean"
                },
                "logo": {
                    "type": "string"
                },
                "member_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "plan": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "internal_delivery_http_payment.VerifyPaymentRequest": {
            "type": "object",
            "properties": {
                "company_id": {
                    "type": "string"
                },
                "invoice_id": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "verified_by": {
                    "type": "string"
                }
            }
        },
        "response.StandardResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "errorCode": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string"
                },
                "stackTrace": {
                    "type": "string"
                },
                "status": {
                    "description": "\"success\" or \"error\"",
                    "type": "string"
                },
                "traceId": {
                    "type": "string"
                },
                "validationErrors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apperror.FieldError"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api-dev.sejutacita.id",
	BasePath:         "/v1/cs-agent-bot",
	Schemes:          []string{},
	Title:            "Customer Service Agent Bot API",
	Description:      "WhatsApp automation bot for Kantorku.id HRIS SaaS",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
